### ISSUE TITLE
Play more than one video at the same time.

### ISSUE THREAD

**Issue by trungnthut** [mzafers/QtVlcMediaPlayer#3]
I tried your lib with Android and it is seem that it could not play more than one video at the same time.
When one play, it block other.

Is there any way to allow it to make it work with 2 or more video at the same time?

**Comment by mzafers** [comment]
In fact, I've implemented the new libvlc api. And I tried this on x86 Android device. It can play 4 video from sdcard at the same time. I will update this repo.

**Comment by trungnthut** [comment]
Cool, can I know when we can get it?

**Comment by mzafers** [comment]
Actually I don't know. Maybe 2 or 3 weeks.

**Comment by trungnthut** [comment]
I kinda need that multiple playing function.
Could you please you push a preview version or may be do you have any hint on playing multiple videos at the same time? If I'm not wrong you also made some singleton stuff under C layer.

**Comment by mzafers** [comment]
I've updated. You can try the new libvlc api.

**Comment by trungnthut** [comment]
Amazing! Thanks!

**Comment by trungnthut** [comment]
It works, but the performance is not as good as the native Android. Is there anyway to tweak the options?

**Comment by mzafers** [comment]
There is another issue about that. I will find a way to pass "libvlc options" to java side.
