### ISSUE TITLE
Broadcast support

### ISSUE THREAD

**Issue by kornava** [mzafers/QtVlcMediaPlayer#5]
Hi,
I just tested your QtVlcMediaPlayer, and it looks great.
is there any way to use the "libvlc_vlm_add_broadcast" function?
In addition to QML, is it possible to access the libvlc methods from C++ part in Qt ?

**Comment by mzafers** [comment]
Hello, thanks for the comment. As far as I know it's not possible. It's java media player implementation only.

**Comment by kornava** [comment]
I just noticed that libvlc_vlm_add_broadcast is not ported to android :(
